const defaultGods = [
    {
        id: 1,
        name: "Apollo (God of Music)",
        power: "Your Move: Your Worker may move one additional time, but not back to its initial space.",
        category: "basic",
    },
    {
        id: 2,
        name: "Artemis (Goddess of the Hunt)",
        power: "Opponent's Turn: If one of your Workers moved up on your last turn, opponent Workers cannot move up this turn.",
        category: "basic",
    },
    {
        id: 3,
        name: "Athena (Goddess of Wisdom)",
        power: "Your Build: Your Worker may build a dome at any level.",
        category: "basic",
    },
    {
        id: 4,
        name: "Atlas (Titan Shouldering the Heavens)",
        power: "Your Build: Your Worker may build one additional time, but not on the same space.",
        category: "basic",
    },
    {
        id: 5,
        name: "Demeter (Goddess of the Harvest)",
        power: "Your Build: Your Worker may build one additional block (not dome) on top of your first block.",
        category: "basic",
    },
    {
        id: 6,
        name: "Hephaestus (God of Blacksmiths)",
        power: "Your Turn: If your Workers do not move up or down, they may each move any number of times (even zero), and then either builds.",
        category: "basic",
    },
    {
        id: 7,
        name: "Hermes (God of Travel)",
        power: "Your Move: Your Worker may move into an opponent Worker’s space, if their Worker can be forced one space straight backwards to an unoccupied space at any level.",
        category: "basic",
    },
    {
        id: 8,
        name: "Minotaur (Bull-headed Monster)",
        power: "Win Condition: You also win if your Worker moves down two or more levels.",
        category: "basic",
    },
    {
        id: 9,
        name: "Pan (God of the Wild)",
        power: "Your Turn: If your Worker does not move up, it may build both before and after moving.",
        category: "basic",
    },
    {
        id: 10,
        name: "Prometheus (Titan Benefactor of Mankind)",
        power: "Your Turn: If your Worker does not move up, it may build both before and after moving.",
        category: "basic",
    },
    {
        id: 11,
        name: "Aphrodite (Goddess of Love)",
        power: "Any Move: If an opponent Worker starts its turn neighboring one of your Workers, its last move must be to a space neighboring one of your Workers.",
        category: "advanced",
    },
    {
        id: 12,
        name: "Ares (God of War)",
        power: "End of Your Turn: You may remove an unoccupied block (not dome) neighboring your unmoved Worker. You also remove any Tokens on the block.",
        category: "advanced",
    },
    {
        id: 13,
        name: "Bia (Goddess of Violence)",
        power: "Setup: Place your Workers first. Your Move: If your Worker moves into a space and the next space in the same direction is occupied by an opponent Worker, the opponent’s Worker is removed from the game.",
        category: "advanced",
    },
    {
        id: 14,
        name: "Charon (Ferryman to the Underworld)",
        power: "Your Move: Before your Worker moves, you may force a neighboring opponent Worker to the space directly on the other side of your Worker, if that space is unoccupied.",
        category: "advanced",
    },
    {
        id: 15,
        name: "Chaos (Primordial Nothingness)",
        power: "Setup: Shuffle all unused Simple God Powers (featuring a symbol) into a face-down deck in your play area. Draw the top God Power, and place it face-up beside the deck.Any Time: You have the Power of the face-up God Power. You must discard your current God Power and draw a new one after any turn in which at least one dome is built. If you run out of God Powers, shuffle them to create a new deck and draw the top one.",
        category: "advanced",
    },
    {
        id: 16,
        name: "Chronus (God of Time)",
        power: "Win Condition: You also win when there are at least five Complete Towers on the board.",
        category: "advanced",
    },
    {
        id: 17,
        name: "Circe (Divine Enchantress)",
        power: "Start of Your Turn: If an opponent’s Workers do not neighbor each other, you alone have use of their power until your next turn.",
        category: "advanced",
    },
    {
        id: 18,
        name: "Dionysus (God of Wine)",
        power: "Your Build: Each time a Worker you control creates a Complete Tower, you may take an additional turn using an opponent Worker instead of your own. No player can win during these additional turns.",
        category: "advanced",
    },
    {
        id: 19,
        name: "Eros (God of Desire)",
        power: "Setup: Place your Workers anywhere along opposite edges of the board. Win Condition: You also win if one of your Workers moves to a space neighboring your other Worker and both are on the first level (or the same level in a 3-player game).",
        category: "advanced",
    },
    {
        id: 20,
        name: "Hera (Goddess of Marriage)",
        power: "Opponent’s Turn: An opponent cannot win by moving into a perimeter space.",
        category: "advanced",
    },
    {
        id: 21,
        name: "Hestia (Goddess of Hearth and Home)",
        power: "Your Build: Your Worker may build one additional time, but this cannot be on a perimeter space.",
        category: "advanced",
    },
    {
        id: 22,
        name: "Hypnus (God of Sleep)",
        power: "Start of Opponent’s Turn: If one of your opponent’s Workers is higher than all of their others, it cannot move.",
        category: "advanced",
    },
    {
        id: 23,
        name: "Limus (Goddess of Famine)",
        power: "Opponent’s Turn: Opponent Workers cannot build on spaces neighboring your Workers, unless building a dome to create a Complete Tower.",
        category: "advanced",
    },
    {
        id: 24,
        name: "Medusa (Petrifying Gorgon)",
        power: "End of Your Turn: If possible, your Workers build in lower neighboring spaces that are occupied by opponent Workers, removing the opponent Workers from the game.",
        category: "advanced",
    },
    {
        id: 25,
        name: "Morpheus (God of dreams)",
        power: "Start of Your Turn: Place a block or dome on your God Power card. Your Build: Your Worker cannot build as normal. Instead, your Worker may build any number of times (even zero) using blocks / domes collected on your God Power card. At any time, any player may exchange a block / dome on the God Power card for dome or a block of a different shape.",
        category: "advanced",
    },
    {
        id: 26,
        name: "Persephone (Goddess of Spring Growth)",
        power: "Opponent’s Turn: If possible, at least one Worker must move up this turn.",
        category: "advanced",
    },
    {
        id: 27,
        name: "Poseidon (God of the Sea)",
        power: "End of Your Turn: If your unmoved Worker is on the ground level, it may build up to three times.",
        category: "advanced",
    },
    {
        id: 28,
        name: "Selene (Goddess of the Moon)",
        power: "Setup: Place a male and a female Worker of your color. Your Build: Instead of your normal build, your female Worker may build a dome at any level regardless of which Worker moved.",
        category: "advanced",
    },
    {
        id: 29,
        name: "Triton (God of the Waves)",
        power: "Your Move: Each time your Worker moves into a perimeter space, it may immediately move again.",
        category: "advanced",
    },
    {
        id: 30,
        name: "Zeus (God of the Sky)",
        power: "Your Build: Your Worker may build a block under itself.",
        category: "advanced",
    },
]

export default defaultGods
